### PR TITLE
Merge pull request #17 from bill7liu/master

### PR DESCRIPTION
**Pull request by liuniverse**
pr from desktop

### CODE REVIEW

**Comment by bill7liu** [comment]
Can one of the admins verify this patch?

**Comment by liuniverse** [comment]
run tests

**Comment by bill7liu** [comment]
run tests

**Comment by bill7liu** [comment]
run tests

**Comment by bill7liu** [comment]
run tests

**Comment by bill7liu** [comment]
run tests

**Comment by bill7liu** [comment]
run tests

**Pull request closed without merging**
